version: '3'

services:
  proxy-server:
    build:
      context: ./proxy-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: web-scraper-proxy
