name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd proxy-server && npm ci
    
    - name: Build proxy server Docker image
      run: |
        cd proxy-server
        docker build -t web-scraper-proxy .
    
    - name: Run tests
      run: npm test
      
    # Add deployment steps here when ready
    # - name: Deploy
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     # Add deployment commands
